runtime: nodejs10

instance_class: F1

env_variables:
  NODE_ENV: "production"
  DATABASE_DIALECT: "postgres"
  DATABASE_HOST: "/cloudsql/burntoast:australia-southeast1:knob"
  DATABASE_PORT: 5432
  DATABASE_NAME: "postgres"
  DATABASE_USERNAME: "toaster"
  DATABASE_PASSWORD: "raisintoast"
  DATABASE_SSL: true
  BEARER: "breadcat"
